#!/usr/bin/env python3
"""Full org-to-Hugo export orchestrator.

Scans the org source tree on every run, exports every currently exportable
file via the matching Emacs batch script, and then removes stale markdown
outputs only after Emacs succeeds.

Unlike the old incremental exporter, this script keeps no manifest.  The
source tree is the ground truth for both what to export and which generated
markdown files are still valid.

Usage:
    python3 scripts/export-org.py notes
    python3 scripts/export-org.py quotes
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from lib import (
    BIBLIO_NOTES_DIR,
    NOTES_DIR,
    REPO_ROOT,
    extract_export_file_names,
    is_dataless,
    safe_remove,
)

SCRIPT_DIR = REPO_ROOT / "scripts"


SECTIONS = {
    "quotes": {
        "source_dirs": [BIBLIO_NOTES_DIR],
        "output_dir": REPO_ROOT / "content/quotes",
        "elisp": SCRIPT_DIR / "export-quotes.el",
        "skip_files": set(),
        # Non-diary quotes are generated by extract-non-diary-quotes.py and
        # cleaned by that script.  The ox-hugo quote export should not move
        # them to Trash on every full diary-quote export.
        "preserve_output": lambda path: "-q-" in path.stem,
    },
    "notes": {
        "source_dirs": [NOTES_DIR],
        "output_dir": REPO_ROOT / "content/notes",
        "elisp": SCRIPT_DIR / "export-notes.el",
        # pablos-miscellany.org is the org-roam top-level index file, not an
        # exportable note.
        "skip_files": {"pablos-miscellany.org"},
        "preserve_output": lambda _path: False,
    },
}


def relpath_for(filepath: Path, source_dirs: list[Path]) -> str:
    """Return the relative path of *filepath* under its source directory."""
    for source_dir in source_dirs:
        try:
            return str(filepath.relative_to(source_dir))
        except ValueError:
            continue
    return str(filepath.relative_to(source_dirs[0]))


def resolve_relpath(relpath: str, source_dirs: list[Path]) -> Path:
    """Resolve a relative source path under the first matching source dir."""
    for source_dir in source_dirs:
        candidate = source_dir / relpath
        if candidate.exists():
            return candidate
    return source_dirs[0] / relpath


def scan_source_files(cfg: dict) -> tuple[dict[str, list[str]], list[Path]]:
    """Return exportable files as {relpath: outputs}, plus skipped dataless files."""
    source_dirs = cfg["source_dirs"]
    skip_files = cfg["skip_files"]

    result: dict[str, list[str]] = {}
    skipped_dataless: list[Path] = []
    org_files: list[Path] = []
    for source_dir in source_dirs:
        org_files.extend(sorted(
            p for p in source_dir.rglob("*.org") if not p.name.startswith(".")
        ))

    total = len(org_files)
    for index, org_file in enumerate(org_files, 1):
        if index % 200 == 0 or index == total:
            print(f"  Scanned {index}/{total} files...", flush=True)
        if org_file.name in skip_files:
            continue
        if org_file.name.endswith("~") or org_file.name.startswith("."):
            continue
        if is_dataless(org_file):
            skipped_dataless.append(org_file)
            continue

        try:
            outputs = extract_export_file_names(org_file)
        except OSError as exc:
            print(f"  Warning: skipping {org_file}: {exc}", file=sys.stderr)
            continue

        if outputs:
            result[relpath_for(org_file, source_dirs)] = outputs

    return result, skipped_dataless


def warn_dataless_files(files: list[Path]) -> None:
    """Warn about cloud-evicted files that could not be scanned."""
    if not files:
        return
    sample = ", ".join(path.name for path in files[:5])
    extra = f" ... and {len(files) - 5} more" if len(files) > 5 else ""
    print(
        f"WARNING: skipped {len(files)} dataless (cloud-evicted) org file(s): "
        f"{sample}{extra}\n"
        "  Export may be incomplete. In Finder, select the affected files, "
        "right-click, and choose 'Make Available Offline'.",
        file=sys.stderr,
    )


def run_emacs(elisp: Path, file_list_path: str) -> int:
    """Run the Emacs batch export over FILE_LIST_PATH."""
    env = os.environ.copy()
    env["EXPORT_FILE_LIST"] = file_list_path

    print("Starting Emacs batch export...")
    print(f"Script: {elisp}\n")

    result = subprocess.run(
        ["emacs", "--batch", "-l", str(elisp)],
        env=env,
        timeout=7200,
    )
    if result.returncode != 0:
        print(f"\nERROR: Emacs exited with code {result.returncode}", file=sys.stderr)
    return result.returncode


def delete_md_files(output_dir: Path, filenames: list[str]) -> int:
    """Move specific markdown files from OUTPUT_DIR to Trash."""
    count = 0
    for name in filenames:
        path = output_dir / name
        if path.exists():
            safe_remove(path)
            print(f"  Removed stale: {name}")
            count += 1
    return count


def remove_stale_outputs(
    output_dir: Path,
    valid_outputs: set[str],
    preserve_output,
) -> int:
    """Remove generated markdown files no longer present in source."""
    stale = [
        path.name
        for path in sorted(output_dir.glob("*.md"))
        if path.name != "_index.md"
        and path.name not in valid_outputs
        and not preserve_output(path)
    ]
    if not stale:
        print("No stale outputs to remove.")
        return 0
    print(f"Removing {len(stale)} stale output(s)...")
    return delete_md_files(output_dir, stale)


def run_export(section: str) -> None:
    """Run a full export for SECTION."""
    cfg = SECTIONS[section]
    source_dirs = cfg["source_dirs"]
    output_dir = cfg["output_dir"]

    for source_dir in source_dirs:
        if not source_dir.exists():
            print(f"ERROR: Source directory not found: {source_dir}", file=sys.stderr)
            sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Full export for {section}")
    print(f"Scanning {', '.join(str(d) for d in source_dirs)} ...")
    current_files, skipped_dataless = scan_source_files(cfg)
    warn_dataless_files(skipped_dataless)

    print(f"Found {len(current_files)} exportable org file(s).")
    if not current_files:
        print("ERROR: no exportable files found; refusing to prune outputs.", file=sys.stderr)
        sys.exit(1)

    valid_outputs = {
        output
        for outputs in current_files.values()
        for output in outputs
    }

    full_paths = [
        str(resolve_relpath(name, source_dirs))
        for name in sorted(current_files)
    ]
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", prefix="export-list-", delete=False
    ) as tmp:
        tmp.write("\n".join(full_paths))
        file_list_path = tmp.name

    try:
        returncode = run_emacs(cfg["elisp"], file_list_path)
    finally:
        os.unlink(file_list_path)

    if returncode != 0:
        print("Export failed; leaving existing outputs untouched.", file=sys.stderr)
        sys.exit(returncode)

    remove_stale_outputs(output_dir, valid_outputs, cfg["preserve_output"])
    print("\nDone.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Full org-to-Hugo export")
    parser.add_argument("section", choices=sorted(SECTIONS), help="Which section to export")
    # Compatibility only: callers can keep passing --full while this exporter
    # remains unconditionally full.
    parser.add_argument("--full", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args()

    run_export(args.section)


if __name__ == "__main__":
    main()
